version: "3.7"
services:
  localstack:
    image: localstack/localstack
    container_name: tusk-localstack
    ports:
      - 4572:4572
    environment:
      - SERVICES=s3
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /tmp/localstack:/tmp/localstack
