name: Test
on: push

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Run localstack
        run: docker run -d localstack/localstack -p 4572:4572 -e SERVICES=s3 -e DOCKER_HOST=unix:///var/run/docker.sock

      - name: Install composer dependencies
        run: |
          composer global require hirak/prestissimo
          composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: PHPUnit
        run: vendor/bin/phpunit

      - name: PHPStan
        run: vendor/bin/phpstan analyse

      - name: Psalm
        run: vendor/bin/psalm

      - name: PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer --dry-run
